{% set name = "splipy" %}
{% set version = "1.5.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Splipy-{{ version }}.tar.gz
    sha256: 400931df9159adcc88e07731c256f1af9f8f4c96babb9a058e6dbad04afdda39
  - path: COPYING
    sha256: 3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - numpy >=1.15
    - python
    - scipy >=1.2

test:
  imports:
    - splipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sintefmath/Splipy
  summary: Spline modelling library for Python
  doc_url: https://pythonhosted.org/Splipy/
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - conda-forger
